// This file is auto-generated by scripts/generate-agent-manifest.ts.
// Do not edit manually.

import type { z } from 'zod';
import * as agentModule0 from '../janitor/index';
import * as agentModule1 from '../hunter/index';
import * as agentModule2 from '../inspector/index';
import * as agentModule3 from '../scribe/index';

export const AGENT_MANIFEST = [
  {
    definition: agentModule0.AGENT_DEFINITION,
    outputSchema: agentModule0.OUTPUT_SCHEMA,
  },
  {
    definition: agentModule1.AGENT_DEFINITION,
    outputSchema: agentModule1.OUTPUT_SCHEMA,
  },
  {
    definition: agentModule2.AGENT_DEFINITION,
    outputSchema: agentModule2.OUTPUT_SCHEMA,
    normalizeFinding: agentModule2.normalizeFinding,
  },
  {
    definition: agentModule3.AGENT_DEFINITION,
    outputSchema: agentModule3.OUTPUT_SCHEMA,
  },
] as const;

export type AgentManifestEntry = {
  definition: (typeof AGENT_MANIFEST)[number]['definition'];
  outputSchema: z.ZodTypeAny;
  normalizeFinding?: (finding: Record<string, unknown>) => void;
};
