/**
 * Sync agent-owned renderer source files into the CLI frontend asset tree.
 *
 * Source convention:
 *   packages/shared/src/agents/<agent>/renderers/<name>-v<N>.js|css
 *
 * Target convention:
 *   packages/cli/src/daemon/frontend/views/reports/finding-enrichments/renderers/agents/<agent>/<name>-v<N>.js|css
 *
 * CSS manifest:
 *   packages/cli/src/daemon/frontend/views/reports/finding-enrichments/renderers/agents/agent-enrichments.generated.css
 *   Contains sorted @import lines for every synced agent CSS file.
 *
 * Behavior:
 * - Deterministic: sorted traversal, stable output.
 * - Validates filename convention (lowercase alphanumeric + hyphens, -vN suffix, .js or .css).
 * - Rejects collisions (two source files mapping to same target path).
 * - Scoped cleanup: removes stale files under agent target directories that
 *   no longer have a corresponding source file.
 * - Generates a CSS manifest that aggregates all agent CSS via @import.
 * - Fails with non-zero exit on any validation error.
 */

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { basename, resolve } from 'node:path';

const RENDERER_FILENAME_PATTERN =
  /^[a-z0-9]+(?:-[a-z0-9]+)*-v[0-9]+\.(js|css)$/;

export const CSS_MANIFEST_FILENAME = 'agent-enrichments.generated.css';

const JS_SYNC_HEADER =
  '// Synced from agent source by sync-agent-renderers. Do not edit.\n';
const CSS_SYNC_HEADER =
  '/* Synced from agent source by sync-agent-renderers. Do not edit. */\n';
const CSS_MANIFEST_HEADER =
  '/* Auto-generated by sync-agent-renderers. Do not edit. */\n';

function syncHeaderFor(filename: string): string {
  return filename.endsWith('.css') ? CSS_SYNC_HEADER : JS_SYNC_HEADER;
}

function isRendererAsset(filename: string): boolean {
  return filename.endsWith('.js') || filename.endsWith('.css');
}

export interface SyncResult {
  copied: string[];
  removed: string[];
  errors: string[];
}

export function resolveSourceDir(repoRoot: string): string {
  return resolve(repoRoot, 'packages/shared/src/agents');
}

export function resolveTargetDir(repoRoot: string): string {
  return resolve(
    repoRoot,
    'packages/cli/src/daemon/frontend/views/reports/finding-enrichments/renderers/agents',
  );
}

export function isValidRendererFilename(filename: string): boolean {
  return RENDERER_FILENAME_PATTERN.test(filename);
}

export interface RendererSourceEntry {
  agent: string;
  filename: string;
  sourcePath: string;
  targetPath: string;
}

/**
 * Discover all agent renderer source files under the shared agents tree.
 * Returns entries sorted by agent then filename for determinism.
 */
export function discoverRendererSources(
  sourceBaseDir: string,
  targetBaseDir: string,
): { entries: RendererSourceEntry[]; errors: string[] } {
  const entries: RendererSourceEntry[] = [];
  const errors: string[] = [];

  if (!existsSync(sourceBaseDir)) {
    return { entries, errors };
  }

  const agentDirs = readdirSync(sourceBaseDir, { withFileTypes: true })
    .filter((d) => d.isDirectory() && d.name !== 'core')
    .map((d) => d.name)
    .sort();

  for (const agent of agentDirs) {
    const renderersDir = resolve(sourceBaseDir, agent, 'renderers');
    if (!existsSync(renderersDir)) {
      continue;
    }

    const files = readdirSync(renderersDir, { withFileTypes: true })
      .filter((f) => f.isFile() && isRendererAsset(f.name))
      .map((f) => f.name)
      .sort();

    for (const filename of files) {
      if (!isValidRendererFilename(filename)) {
        errors.push(
          `Invalid renderer filename: ${agent}/renderers/${filename} (must match ${RENDERER_FILENAME_PATTERN.source})`,
        );
        continue;
      }

      entries.push({
        agent,
        filename,
        sourcePath: resolve(renderersDir, filename),
        targetPath: resolve(targetBaseDir, agent, filename),
      });
    }
  }

  return { entries, errors };
}

/**
 * Detect target path collisions (two different source files mapping to the
 * same target). This should never happen with the current naming convention
 * but guards against future mistakes.
 */
export function detectCollisions(entries: RendererSourceEntry[]): string[] {
  const seen = new Map<string, string>();
  const errors: string[] = [];

  for (const entry of entries) {
    const existing = seen.get(entry.targetPath);
    if (existing) {
      errors.push(
        `Collision: ${entry.sourcePath} and ${existing} both map to ${entry.targetPath}`,
      );
    } else {
      seen.set(entry.targetPath, entry.sourcePath);
    }
  }

  return errors;
}

/**
 * Find stale files in agent target directories that no longer have a
 * corresponding source entry. Only inspects directories for agents that
 * have at least one source entry (scoped cleanup).
 */
export function findStaleTargetFiles(
  entries: RendererSourceEntry[],
  targetBaseDir: string,
): string[] {
  const validTargets = new Set(entries.map((e) => e.targetPath));
  const stale: string[] = [];

  // Also check agent dirs in target that have no source entries at all
  if (existsSync(targetBaseDir)) {
    const targetAgentDirs = readdirSync(targetBaseDir, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name)
      .sort();

    for (const agent of targetAgentDirs) {
      const agentTargetDir = resolve(targetBaseDir, agent);
      const files = readdirSync(agentTargetDir, { withFileTypes: true })
        .filter((f) => f.isFile() && isRendererAsset(f.name))
        .map((f) => f.name)
        .sort();

      for (const filename of files) {
        const targetPath = resolve(agentTargetDir, filename);
        if (!validTargets.has(targetPath)) {
          stale.push(targetPath);
        }
      }
    }
  }

  return stale;
}

/**
 * Generate a CSS manifest that imports all synced agent CSS files.
 * Returns the full file content, or empty string if no CSS entries exist.
 */
export function generateCssManifest(entries: RendererSourceEntry[]): string {
  const cssEntries = entries.filter((e) => e.filename.endsWith('.css'));

  if (cssEntries.length === 0) {
    return '';
  }

  const imports = cssEntries
    .map((e) => `@import "./${e.agent}/${e.filename}";`)
    .join('\n');

  return CSS_MANIFEST_HEADER + imports + '\n';
}

/**
 * Execute the full sync pipeline.
 */
export function syncAgentRenderers(repoRoot: string): SyncResult {
  const sourceBaseDir = resolveSourceDir(repoRoot);
  const targetBaseDir = resolveTargetDir(repoRoot);

  const { entries, errors: discoveryErrors } = discoverRendererSources(
    sourceBaseDir,
    targetBaseDir,
  );

  const collisionErrors = detectCollisions(entries);
  const allErrors = [...discoveryErrors, ...collisionErrors];

  if (allErrors.length > 0) {
    return { copied: [], removed: [], errors: allErrors };
  }

  // Find stale files before copying (so we can report them)
  const staleFiles = findStaleTargetFiles(entries, targetBaseDir);

  // Remove stale files
  const removed: string[] = [];
  for (const stalePath of staleFiles) {
    rmSync(stalePath, { force: true });
    removed.push(stalePath);
  }

  // Copy source -> target
  const copied: string[] = [];
  for (const entry of entries) {
    const targetDir = resolve(targetBaseDir, entry.agent);
    mkdirSync(targetDir, { recursive: true });

    const content = readFileSync(entry.sourcePath, 'utf-8');
    const existing = existsSync(entry.targetPath)
      ? readFileSync(entry.targetPath, 'utf-8')
      : null;
    const synced = syncHeaderFor(entry.filename) + content;

    if (existing !== synced) {
      writeFileSync(entry.targetPath, synced);
      copied.push(entry.targetPath);
    }
  }

  // Generate CSS manifest
  const manifestPath = resolve(targetBaseDir, CSS_MANIFEST_FILENAME);
  const manifestContent = generateCssManifest(entries);

  if (manifestContent) {
    mkdirSync(targetBaseDir, { recursive: true });
    const existingManifest = existsSync(manifestPath)
      ? readFileSync(manifestPath, 'utf-8')
      : null;
    if (existingManifest !== manifestContent) {
      writeFileSync(manifestPath, manifestContent);
      copied.push(manifestPath);
    }
  } else if (existsSync(manifestPath)) {
    rmSync(manifestPath, { force: true });
    removed.push(manifestPath);
  }

  return { copied, removed, errors: [] };
}

// CLI entrypoint
if (import.meta.main) {
  const repoRoot = resolve(import.meta.dir, '../../..');
  const result = syncAgentRenderers(repoRoot);

  if (result.errors.length > 0) {
    for (const error of result.errors) {
      console.error(`ERROR: ${error}`);
    }
    process.exit(1);
  }

  if (result.removed.length > 0) {
    for (const file of result.removed) {
      console.log(`removed: ${file}`);
    }
  }

  if (result.copied.length > 0) {
    for (const file of result.copied) {
      console.log(`synced: ${file}`);
    }
  }

  if (result.copied.length === 0 && result.removed.length === 0) {
    console.log('sync: up to date');
  }
}
