import { readdir, readFile, stat, writeFile } from 'node:fs/promises';
import { join, relative } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

type LoadedAgentModule = {
  AGENT_DEFINITION?: { id?: string };
  OUTPUT_SCHEMA?: unknown;
  ORDER?: number;
  normalizeFinding?: unknown;
};

type AgentModuleRecord = {
  dirName: string;
  relativeImportPath: string;
  definitionId: string;
  order: number;
  hasNormalizeFinding: boolean;
};

const SCRIPT_DIR = fileURLToPath(new URL('.', import.meta.url));
const PACKAGE_ROOT = join(SCRIPT_DIR, '..');
const AGENTS_DIR = join(PACKAGE_ROOT, 'src', 'agents');
const OUTPUT_FILE = join(
  PACKAGE_ROOT,
  'src',
  'agents',
  'core',
  'manifest.generated.ts',
);

const CHECK_MODE = process.argv.includes('--check');

function normalizeImportPath(targetPath: string): string {
  const outputDir = join(PACKAGE_ROOT, 'src', 'agents', 'core');
  const rel = relative(outputDir, targetPath).split('\\').join('/');
  return rel.replace(/\.ts$/u, '');
}

async function loadAgentModule(
  indexFilePath: string,
): Promise<LoadedAgentModule> {
  const cacheBuster = `?t=${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
  const moduleUrl = `${pathToFileURL(indexFilePath).href}${cacheBuster}`;
  return (await import(moduleUrl)) as LoadedAgentModule;
}

async function discoverAgentModules(): Promise<AgentModuleRecord[]> {
  const directoryEntries = await readdir(AGENTS_DIR, { withFileTypes: true });
  const records: AgentModuleRecord[] = [];

  for (const entry of directoryEntries) {
    if (!entry.isDirectory() || entry.name === 'core') {
      continue;
    }

    const indexFilePath = join(AGENTS_DIR, entry.name, 'index.ts');
    try {
      await stat(indexFilePath);
    } catch {
      continue;
    }

    const loaded = await loadAgentModule(indexFilePath);
    const definitionId = loaded.AGENT_DEFINITION?.id;
    const order = loaded.ORDER;

    if (typeof definitionId !== 'string' || definitionId.length === 0) {
      throw new Error(`Missing AGENT_DEFINITION.id in ${indexFilePath}`);
    }
    if (!Number.isInteger(order)) {
      throw new Error(`Missing numeric ORDER in ${indexFilePath}`);
    }
    if (loaded.OUTPUT_SCHEMA === undefined) {
      throw new Error(`Missing OUTPUT_SCHEMA export in ${indexFilePath}`);
    }

    records.push({
      dirName: entry.name,
      relativeImportPath: normalizeImportPath(indexFilePath),
      definitionId,
      order: order as number,
      hasNormalizeFinding: typeof loaded.normalizeFinding === 'function',
    });
  }

  return records.sort(
    (left, right) =>
      left.order - right.order ||
      left.definitionId.localeCompare(right.definitionId),
  );
}

function renderManifestSource(records: AgentModuleRecord[]): string {
  const importLines = records.map(
    (record, index) =>
      `import * as agentModule${index} from '${record.relativeImportPath}';`,
  );

  const manifestLines = records.map((record, index) => {
    const normalizeLine = record.hasNormalizeFinding
      ? `,\n    normalizeFinding: agentModule${index}.normalizeFinding`
      : '';
    return `  {\n    definition: agentModule${index}.AGENT_DEFINITION,\n    outputSchema: agentModule${index}.OUTPUT_SCHEMA${normalizeLine},\n  },`;
  });

  return `// This file is auto-generated by scripts/generate-agent-manifest.ts.
// Do not edit manually.

import type { z } from 'zod';
${importLines.join('\n')}

export const AGENT_MANIFEST = [
${manifestLines.join('\n')}
] as const;

export type AgentManifestEntry = {
  definition: (typeof AGENT_MANIFEST)[number]['definition'];
  outputSchema: z.ZodTypeAny;
  normalizeFinding?: (finding: Record<string, unknown>) => void;
};
`;
}

async function run(): Promise<void> {
  const records = await discoverAgentModules();
  const nextContent = renderManifestSource(records);

  let previousContent = '';
  try {
    previousContent = await readFile(OUTPUT_FILE, 'utf8');
  } catch {
    previousContent = '';
  }

  if (CHECK_MODE) {
    if (previousContent !== nextContent) {
      throw new Error(
        'Agent manifest is out of date. Run bun run generate:agents.',
      );
    }
    return;
  }

  if (previousContent !== nextContent) {
    await writeFile(OUTPUT_FILE, nextContent, 'utf8');
  }
}

run().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
